### ISSUE TITLE
Google Speech API v2 

### ISSUE THREAD

**Issue by legend0011** [psirenny/node-google-speech-api#5]
I would like to use Google Speech API v2 to generate asr(auto speech recognition) result for .wav files for experiment use.

I make some changes to a project on GitHub: Uberi https://github.com/Uberi/speech_recognition And I apply for my own API key, and I can only access the API for about 500 times a day.

Do you know how to make 5000 or more request(access to the API)? Or how google block us??

Thanks very much !!!

**Comment by psirenny** [comment]
In google developer console you can view how many requests you've made to google's speech API as well as what your daily limit is. AFAIK, the free tier (which is probably what you are on) only allows 50 requests per day.

There is a link on that same page to bump your quota up. I've never upgraded my account so I don't know what the pricing would be like for 5000 requests. I also get a permission error when I click that link... but I'm sure you could contact google in some other way to get them to take your money.

Good luck
